name: Create Release and Generate Changelog

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Changelog
        id: changelog
        run: |-
          last_tag=$(git describe --tags --abbrev=0)
          [[ -z "$last_tag" ]] && last_tag="$(git log --reverse --format="format:%H" | head -1)"
          changelog=$(git log ${last_tag}..HEAD --oneline --no-merges --pretty=format:"%h %s")
          echo "::set-output name=changelog::$changelog"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
