name: Create Release and Generate Changelog

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Changelog
        id: changelog
        run: |-
          current_tag=$(git describe --tags --abbrev=0)
          previous_tag=$(git describe --tags --abbrev=0 "${current_tag}^")

          if [[ -z "$previous_tag" ]]
          then
            previous_tag="$(git log --reverse --format="format:%H" | head -1)"
          fi

          changelog=$(git log ${previous_tag}..${current_tag} --oneline --no-merges --pretty=format:"%h %s")
          echo "changelog=$changelog" > $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
